# @file home/modules/power.nix
# @description Laptop power management and thermal optimization
# @update-policy Update when new power-saving features or hardware support added

{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.power;
  
  # Detect if system is a laptop (has battery)
  isLaptop = builtins.pathExists "/sys/class/power_supply/BAT0" ||
             builtins.pathExists "/sys/class/power_supply/BAT1";
  
  # TLP configuration file
  tlpConfig = pkgs.writeText "tlp.conf" ''
    # TLP Configuration for Laptop Power Management
    # Auto-generated by geckoforge home/modules/power.nix
    
    # ===== CPU Management =====
    CPU_SCALING_GOVERNOR_ON_AC=${cfg.cpu.governorAC}
    CPU_SCALING_GOVERNOR_ON_BAT=${cfg.cpu.governorBattery}
    
    ${optionalString cfg.cpu.enableIntelPstate ''
    # Intel P-state driver
    CPU_ENERGY_PERF_POLICY_ON_AC=performance
    CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
    ''}
    
    # Turbo boost
    CPU_BOOST_ON_AC=${if cfg.cpu.turboAC then "1" else "0"}
    CPU_BOOST_ON_BAT=${if cfg.cpu.turboBattery then "1" else "0"}
    
    ${optionalString (cfg.cpu.maxFreqAC != null) ''
    CPU_SCALING_MAX_FREQ_ON_AC=${toString cfg.cpu.maxFreqAC}
    ''}
    ${optionalString (cfg.cpu.maxFreqBattery != null) ''
    CPU_SCALING_MAX_FREQ_ON_BAT=${toString cfg.cpu.maxFreqBattery}
    ''}
    
    # ===== Battery Thresholds =====
    ${optionalString cfg.battery.enableThresholds ''
    START_CHARGE_THRESH_BAT0=${toString cfg.battery.startThreshold}
    STOP_CHARGE_THRESH_BAT0=${toString cfg.battery.stopThreshold}
    ''}
    
    # ===== Platform Profile =====
    PLATFORM_PROFILE_ON_AC=performance
    PLATFORM_PROFILE_ON_BAT=low-power
    
    # ===== Storage =====
    DISK_DEVICES="${concatStringsSep " " cfg.storage.devices}"
    DISK_APM_LEVEL_ON_AC="${concatStringsSep " " (map toString cfg.storage.apmAC)}"
    DISK_APM_LEVEL_ON_BAT="${concatStringsSep " " (map toString cfg.storage.apmBattery)}"
    
    AHCI_RUNTIME_PM_ON_AC=on
    AHCI_RUNTIME_PM_ON_BAT=auto
    
    # ===== PCI Express =====
    PCIE_ASPM_ON_AC=default
    PCIE_ASPM_ON_BAT=powersupersave
    
    # ===== Graphics =====
    RUNTIME_PM_ON_AC=on
    RUNTIME_PM_ON_BAT=auto
    
    # ===== USB =====
    USB_AUTOSUSPEND=${if cfg.usb.autosuspend then "1" else "0"}
    ${optionalString (cfg.usb.denylist != []) ''
    USB_DENYLIST="${concatStringsSep " " cfg.usb.denylist}"
    ''}
    
    # ===== Wireless =====
    WIFI_PWR_ON_AC=off
    WIFI_PWR_ON_BAT=on
    
    # ===== Audio =====
    SOUND_POWER_SAVE_ON_AC=0
    SOUND_POWER_SAVE_ON_BAT=1
    
    # ===== Radio Devices =====
    DEVICES_TO_ENABLE_ON_STARTUP="bluetooth wifi"
  '';
  
in

{
  options.programs.power = {
    enable = mkEnableOption "laptop power management and thermal optimization";
    
    cpu = {
      governorAC = mkOption {
        type = types.str;
        default = "performance";
        description = "CPU governor when on AC power";
      };
      
      governorBattery = mkOption {
        type = types.str;
        default = "powersave";
        description = "CPU governor when on battery";
      };
      
      enableIntelPstate = mkOption {
        type = types.bool;
        default = true;
        description = "Enable Intel P-state driver optimizations";
      };
      
      turboAC = mkOption {
        type = types.bool;
        default = true;
        description = "Enable CPU turbo boost on AC power";
      };
      
      turboBattery = mkOption {
        type = types.bool;
        default = false;
        description = "Enable CPU turbo boost on battery (drains battery faster)";
      };
      
      maxFreqAC = mkOption {
        type = types.nullOr types.int;
        default = null;
        example = 5000000;
        description = "Maximum CPU frequency on AC (Hz, null = no limit)";
      };
      
      maxFreqBattery = mkOption {
        type = types.nullOr types.int;
        default = 3200000;
        example = 3200000;
        description = "Maximum CPU frequency on battery (Hz)";
      };
    };
    
    battery = {
      enableThresholds = mkOption {
        type = types.bool;
        default = true;
        description = "Enable battery charge thresholds (if hardware supports)";
      };
      
      startThreshold = mkOption {
        type = types.int;
        default = 40;
        description = "Start charging when below this percentage";
      };
      
      stopThreshold = mkOption {
        type = types.int;
        default = 80;
        description = "Stop charging at this percentage (extends battery life)";
      };
    };
    
    storage = {
      devices = mkOption {
        type = types.listOf types.str;
        default = [ "nvme0n1" "sda" ];
        description = "Storage devices to manage";
      };
      
      apmAC = mkOption {
        type = types.listOf types.int;
        default = [ 254 254 ];
        description = "APM levels on AC (254 = max performance)";
      };
      
      apmBattery = mkOption {
        type = types.listOf types.int;
        default = [ 128 128 ];
        description = "APM levels on battery (128 = balanced)";
      };
    };
    
    usb = {
      autosuspend = mkOption {
        type = types.bool;
        default = true;
        description = "Enable USB autosuspend for power saving";
      };
      
      denylist = mkOption {
        type = types.listOf types.str;
        default = [];
        example = [ "046d:c52b" ];
        description = "USB devices to exclude from autosuspend (vendor:product)";
      };
    };
    
    thermal = {
      monitoring = mkOption {
        type = types.bool;
        default = true;
        description = "Install thermal monitoring tools";
      };
    };
  };
  
  config = mkIf cfg.enable {
    # Only warn if not a laptop
    warnings = optional (!isLaptop)
      "Power management module enabled but no battery detected. This module is designed for laptops.";
    
    # Install power management tools
    home.packages = with pkgs; [
      powertop
      lm_sensors
      acpi  # Battery status
    ] ++ optionals cfg.thermal.monitoring [
      stress
      s-tui  # Terminal UI for monitoring
    ];
    
    # PERF: Kernel sysctl parameters for performance (for reference/documentation)
    # These require root access, so we create a reference file
    xdg.configFile."sysctl.d/99-geckoforge-performance.conf".text = ''
      # Memory Management - Desktop/Development Workload Optimization
      vm.swappiness = 10                    # Prefer RAM over swap (default: 60)
      vm.vfs_cache_pressure = 50            # Keep directory cache longer (default: 100)
      vm.dirty_ratio = 10                   # Start background writes earlier (default: 20)
      vm.dirty_background_ratio = 5         # More aggressive background writes (default: 10)
      vm.max_map_count = 2147483642         # Increase for games and containers
      
      # File System Performance
      fs.file-max = 2097152                 # Increase open file limit
      fs.inotify.max_user_watches = 524288  # VS Code, Docker, file watchers
      
      # Network Performance (optional, commented out by default)
      # net.core.rmem_max = 134217728
      # net.core.wmem_max = 134217728
      # net.ipv4.tcp_rmem = 4096 87380 134217728
      # net.ipv4.tcp_wmem = 4096 65536 134217728
    '';
    
    # Activation message for sysctl configuration
    home.activation.sysctlInfo = lib.hm.dag.entryAfter ["writeBoundary"] ''
      echo "[power] Sysctl performance parameters generated at ~/.config/sysctl.d/99-geckoforge-performance.conf"
      echo "[power] To apply system-wide: sudo cp ~/.config/sysctl.d/99-geckoforge-performance.conf /etc/sysctl.d/"
      echo "[power] Then run: sudo sysctl --system"
    '';
    
    # TLP configuration (system-level, shown for reference)
    # User must run: sudo cp ~/.config/tlp/tlp.conf /etc/tlp.conf
    xdg.configFile."tlp/tlp.conf".source = tlpConfig;
    
    # Intel GPU power management modprobe config (for reference)
    xdg.configFile."modprobe.d/i915.conf".text = mkIf cfg.cpu.enableIntelPstate ''
      # Intel iGPU power management
      options i915 enable_guc=3 enable_fbc=1 enable_psr=1
    '';
    
    # Thermal monitoring script
    home.file.".local/bin/check-thermals" = mkIf cfg.thermal.monitoring {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Thermal monitoring for laptops
        
        echo "=== Laptop Thermal Status ==="
        echo ""
        
        # CPU temperatures
        if command -v sensors >/dev/null; then
            echo "CPU Temperatures:"
            ${pkgs.lm_sensors}/bin/sensors | grep -E "(Core|Package)" || echo "  N/A"
            echo ""
        fi
        
        # GPU temperatures (NVIDIA)
        if command -v nvidia-smi >/dev/null; then
            echo "GPU Status:"
            nvidia-smi --query-gpu=name,temperature.gpu,power.draw,clocks.gr,utilization.gpu --format=csv,noheader
            echo ""
        fi
        
        # Battery status
        for bat in /sys/class/power_supply/BAT*; do
            if [ -d "$bat" ]; then
                echo "Battery: $(basename $bat)"
                echo "  Status: $(cat $bat/status)"
                echo "  Capacity: $(cat $bat/capacity)%"
                echo ""
            fi
        done
        
        # CPU throttling check
        if [ -f /sys/devices/system/cpu/cpu0/thermal_throttle/package_throttle_count ]; then
            THROTTLE=$(cat /sys/devices/system/cpu/cpu0/thermal_throttle/package_throttle_count)
            echo "CPU Thermal Throttle Events: $THROTTLE"
            [ "$THROTTLE" -gt 0 ] && echo "⚠ CPU is throttling due to heat!"
        fi
      '';
    };
    
    # Power status script
    home.file.".local/bin/power-status" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Quick power status check
        
        echo "=== Power Management Status ==="
        echo ""
        
        # TLP status (if available)
        if command -v tlp-stat >/dev/null && [ -f /etc/tlp.conf ]; then
            echo "TLP Configuration: Active"
            sudo ${pkgs.tlp}/bin/tlp-stat -s
        else
            echo "TLP: Not configured"
            echo "  Install: sudo zypper install tlp"
            echo "  Configure: sudo cp ~/.config/tlp/tlp.conf /etc/tlp.conf"
            echo "  Enable: sudo systemctl enable --now tlp"
        fi
        
        echo ""
        echo "Battery Status:"
        ${pkgs.acpi}/bin/acpi -V 2>/dev/null || echo "  Install acpi for battery info"
        
        echo ""
        echo "CPU Governor:"
        cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor 2>/dev/null | sort -u || echo "  N/A"
      '';
    };
    
    # Activation message
    home.activation.powerManagementInfo = lib.hm.dag.entryAfter ["writeBoundary"] ''
      ${optionalString cfg.enable ''
        echo "[power] Laptop power management configuration created"
        echo "[power] TLP config: ~/.config/tlp/tlp.conf"
        echo "[power] To apply system-wide:"
        echo "  sudo cp ~/.config/tlp/tlp.conf /etc/tlp.conf"
        echo "  sudo systemctl enable --now tlp"
        echo ""
        echo "[power] Thermal monitoring: check-thermals"
        echo "[power] Power status: power-status"
      ''}
    '';
    
    # Shell aliases
    programs.bash.shellAliases = mkIf config.programs.bash.enable {
      temps = "check-thermals";
      battery = "acpi -V";
      power = "power-status";
    };
    
    programs.zsh.shellAliases = mkIf config.programs.zsh.enable {
      temps = "check-thermals";
      battery = "acpi -V";
      power = "power-status";
    };
  };
}
