# @file home/modules/thunderbird.nix
# @description Hardened Thunderbird email client with anti-phishing and privacy settings
# @update-policy Update when Thunderbird security settings need adjustment

{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.programs.thunderbird-hardened;
in
{
  options.programs.thunderbird-hardened = {
    enable = mkEnableOption "Hardened Thunderbird configuration";

    disableLinks = mkOption {
      type = types.bool;
      default = true;
      description = "Disable clickable links in emails (anti-phishing)";
    };

    disableRemoteContent = mkOption {
      type = types.bool;
      default = true;
      description = "Block remote content and tracking pixels";
    };

    preferPlainText = mkOption {
      type = types.bool;
      default = true;
      description = "Prefer plain text over HTML emails";
    };

    disableTelemetry = mkOption {
      type = types.bool;
      default = true;
      description = "Disable Mozilla telemetry and crash reporting";
    };
  };

  config = mkIf cfg.enable {
    # Create Thunderbird profile directory with hardened settings
    home.file.".thunderbird/profiles.ini" = {
      text = ''
        [Install4F96D1932A9F858E]
        Default=geckoforge.default
        Locked=1

        [Profile0]
        Name=default
        IsRelative=1
        Path=geckoforge.default
        Default=1

        [General]
        StartWithLastProfile=1
        Version=2
      '';
    };

    home.file.".thunderbird/geckoforge.default/user.js" = {
      text = ''
        // Geckoforge Hardened Thunderbird Configuration
        // Generated by home-manager
        // Rev. 2025-10-11

        // ============================================
        // ANTI-PHISHING: Disable Clickable Links
        // ============================================
        ${optionalString cfg.disableLinks ''
        // Prevents accidental clicks on phishing links
        user_pref("network.protocol-handler.external-default", false);
        user_pref("network.protocol-handler.warn-external.http", true);
        user_pref("network.protocol-handler.warn-external.https", true);
        user_pref("network.protocol-handler.warn-external.ftp", true);
        ''}

        // ============================================
        // PRIVACY: Block Remote Content
        // ============================================
        ${optionalString cfg.disableRemoteContent ''
        // Blocks tracking pixels and external images
        user_pref("mailnews.message_display.disable_remote_image", true);
        user_pref("permissions.default.image", 2); // 1=allow, 2=block, 3=allow from originating site only
        ''}

        // ============================================
        // DISPLAY: Plain Text Preference
        // ============================================
        ${optionalString cfg.preferPlainText ''
        // Display emails as plain text by default
        user_pref("mailnews.display.prefer_plaintext", true);
        user_pref("mailnews.display.disallow_mime_handlers", 3); // 0=use handlers, 3=plain text only
        user_pref("mailnews.display.html_as", 1); // 0=html, 1=plain text, 2=simple html, 3=sanitized
        ''}

        // ============================================
        // PRIVACY: Disable Telemetry & Tracking
        // ============================================
        ${optionalString cfg.disableTelemetry ''
        user_pref("datareporting.healthreport.uploadEnabled", false);
        user_pref("datareporting.policy.dataSubmissionEnabled", false);
        user_pref("toolkit.telemetry.enabled", false);
        user_pref("toolkit.telemetry.unified", false);
        user_pref("toolkit.telemetry.archive.enabled", false);
        user_pref("breakpad.reportURL", "");
        user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", false);
        ''}

        // ============================================
        // SECURITY: Additional Hardening
        // ============================================
        // Disable JavaScript in emails (already default, but ensure)
        user_pref("javascript.enabled", false);
        
        // Require encrypted connections when available
        user_pref("mail.smtpserver.default.try_ssl", 3); // 0=never, 1=try, 2=always, 3=if available
        
        // Enable junk mail controls
        user_pref("mail.spam.manualMark", true);
        user_pref("mail.spam.logging.enabled", true);
        
        // Disable automatic updates (handled by system package manager)
        user_pref("app.update.auto", false);
        user_pref("app.update.enabled", false);
        
        // Disable WebGL (reduces attack surface)
        user_pref("webgl.disabled", true);
        
        // ============================================
        // UX: Reasonable Defaults
        // ============================================
        // Mark messages as read after 0 seconds (immediate)
        user_pref("mailnews.mark_message_read.delay", false);
        
        // Show full email addresses
        user_pref("mail.showCondensedAddresses", false);
        
        // Confirm before sending
        user_pref("mail.compose.add_undisclosed_recipients", true);
      '';
    };

    # Create default account templates directory
    home.file.".thunderbird/geckoforge.default/README.txt" = {
      text = ''
        Geckoforge Thunderbird Profile
        ==============================

        This Thunderbird profile has been hardened for security:
        
        ✓ Clickable links disabled (copy/paste URLs manually)
        ✓ Remote content blocked (no tracking pixels)
        ✓ Plain text email preference
        ✓ Telemetry disabled
        
        Email Provider Setup:
        ---------------------
        
        Gmail:
        - IMAP: imap.gmail.com:993 (SSL/TLS)
        - SMTP: smtp.gmail.com:587 (STARTTLS)
        - Enable "Less secure app access" OR use OAuth2
        - App password recommended if 2FA enabled
        
        Outlook/Office 365:
        - IMAP: outlook.office365.com:993 (SSL/TLS)
        - SMTP: smtp.office365.com:587 (STARTTLS)
        - Use OAuth2 authentication (recommended)
        
        ProtonMail:
        - Requires ProtonMail Bridge (see setup script)
        - IMAP: 127.0.0.1:1143 (STARTTLS)
        - SMTP: 127.0.0.1:1025 (STARTTLS)
        - Run: ~/bin/protonmail-bridge --cli
        
        For detailed setup instructions, see:
        ~/git/geckoforge/docs/thunderbird-setup.md
      '';
    };

    # Set as default email handler
    xdg.mimeApps.defaultApplications = {
      "x-scheme-handler/mailto" = "thunderbird.desktop";
      "message/rfc822" = "thunderbird.desktop";
    };
  };
}